Auth_Referral_System/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("account/", include("account.urls")),
    path("referral/", include("referral.urls")),
    path("api/", include("api.urls")),
    # email verification url
    path('verification/', include('verify_email.urls')),
    path("password_reset/",
		auth_views.PasswordResetView.as_view(
			template_name= "account/password-reset.html"
		),
		name= "password_reset"
	),
	path("password_reset_done/",
		auth_views.PasswordResetDoneView.as_view(
			template_name= "account/password-reset-done.html"
		),
		name= "password_reset_done"
	),
	path("password_reset_confirm/<uidb64>/<token>/",
		auth_views.PasswordResetConfirmView.as_view(
			template_name= "account/password-reset-confirm.html"
		),
		name= "password_reset_confirm"
	),
	path("password_reset_complete/",
		auth_views.PasswordResetCompleteView.as_view(
			template_name= "account/password-reset-complete.html"
		),
		name= "password_reset_complete"
	),
	path("oauth/", include("social_django.urls", namespace="social")),
]

account/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = "account"
urlpatterns = [
	path("signup/", signup, name= "signup"),
	path("login/",
		auth_views.LoginView.as_view(
		template_name="account/login.html",
		redirect_authenticated_user= True),
		name= "login"
	),
	path("signup-referral/<str:referral_code>/",
		signup_with_referral,
		name= "signup_with_referral"
	),
	path("logout/",
		auth_views.LogoutView.as_view(
		template_name= "account/logout.html"),
		name= "logout"
	),
	path("settings/", settings_view, name='settings'),
	path("settings/change-password/",
		settings_password_change,
		name="settings_password_change"),
]

api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
	TokenObtainPairView,
	TokenRefreshView,
	TokenVerifyView
)


urlpatterns = [
	path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
	path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
	path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
	path("", index, name= "index"),
	path("referral-notifications/",
		view_notification,
		name= "view_notification"
	),
]

main/views.py
from django.shortcuts import render
from account.models import User
from referral.models import Referral, ReferralNotification


def index(request):
	if request.user.is_authenticated:
		referral_code = Referral.objects.get(user= request.user).referral_code
	else:
		referral_code = ""
	context = {
		"referral_code": referral_code
	}
	return render(request, "main/index.html", context)
	
	
def view_notification(request):
	if request.user.is_authenticated:
		notifications = ReferralNotification.objects.filter(user= request.user).order_by("-date_created")
	else:
		notifications = ""
	context = {
		"notifications": notifications
	}
	return render(request, "main/notification.html", context)

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>{% block title %} {% endblock %}</title>
</head>
<body>
	<nav>
		<div class="nav-links">
			<ul>
				<li><a href="{% url 'main:view_notification' %}"><i class="fa fa-bell" id="ai" onmouseover="showPopBox(p);" onmouseout="hidePopBox();"></i></a></li>
				<li><a href="{% url 'main:index' %}"><i class="fa fa-home" id="hi" onmouseover="showPopBox(h);" onmouseout="hidePopBox();"></i></a></li>
				{% if request.user.is_authenticated %}
				<li><a href="{% url 'account:logout' %}"><i class="fa fa-sign-out" id="si" onmouseover="showPopBox(s);" onmouseout="hidePopBox();"></i></a></li>
				{% else %}
				<li><a href="{% url 'account:login' %}"><i class="fa fa-sign-in" id="si" onmouseover="showPopBox(s);" onmouseout="hidePopBox();"></i></a></li>
				{% endif %}
			</ul>
		</div>
	</nav>
	
	<div class="show-link">
		<ul>
			<li class="notice" id="p">notification</li>
			<li class="notice" id="h">home</li>
			{% if request.user.is_authenticated %}
			<li class="notice" id="s">logout</li>
			{% else %}
			<li class="notice" id="s">sign in</li>
			{% endif %}
		</ul>
	</div>
	
	<div>
		
		{% block content %}
	
		{% endblock %}
		
	</div>
	
	<script>
		var p = document.getElementById("p");
		var h = document.getElementById("h");
		var s = document.getElementById("s");
		
		function hidePopBox () 
			{
				p.style.visibility = "";
				h.style.visibility = "";
				s.style.visibility = "";
			}		
			
		function showPopBox(arg)
		{
			if (arg.style.visibility == "")
			{
				hidePopBox();
				arg.style.visibility = "visible";
			} else {
				arg.style.visibility = "";
			}
		}
	
	</script>
	
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %} Home {% endblock %}


{% block content %}

	<div class= "container">
		<h2 align= "center">Home</h2>
		<p>Referral Link</p>
		<span>http://127.0.0.1:8000/account/signup-referral/{{ referral_code }}</span>
	</div>

{% endblock %}

main/templates/main/notification.html
{% extends 'main/base.html' %}
{% block title %} Notification {% endblock %}


{% block content %}

	<div class= "container">
	<br>
		<h2 align= "center">Notifications</h2>
		{% if notifications %}
			{% for notification in notifications %}
				<div class= "alert alert-info">
					{{ notification }}
					<br>
					<span>{{ notification.date_created }}</span>
				</div>
			{% endfor %}
		{% else %}
			<div class= "alert alert-info">
				You have no notification.
			</div>
		{% endif %}
	</div>

{% endblock %}